package constructors;

public class ConstructorsDemo1 {
	
	//default constructor generated by compiler
	/*
	 * ConstructorsDemo1(){
	 * 
	 * }
	 */
	
	
	
	
	public static void main(String[] args) {
		
		ConstructorsDemo1 obj = new ConstructorsDemo1();
		
	}

}


/*
Constructors:
Constructors are used to initialize the values to instance variables at the time of object creation.

Rules:
1. Constructor name and class name must be same.
2. Access modifiers are applicable for constructors (public, private, protected, default)
3. Parameters can be passed to the constructor.
4. Return type concept is not applicable for the constructor.

syntax:
[access_modifier] classname([parameters_list]){
	--
	--
	--
	--

}


There are 2 types of constructors:
1. Default Constructor: 
If we have not declared any constructor, then JVM will create 0-arg constructor with empty implementation internally.
the constructor generated by compiler is called default constructor.

2. User Defined Constructor
	i. 0-arg or no-arg constructor
	ii. Parameterized constructor


*/